//! Groth16 verification key: the compile-time embedded BN254 key and helpers to
//! build a [`VerificationKey`] from raw byte constants.
//!
//! The key bytes are generated by `build.rs` and pulled in via `include!` below.
//! `contract.rs` consumes [`embedded_vk`] to verify proofs without touching
//! persistent storage.

use soroban_sdk::{
    BytesN, Env, Vec,
    crypto::bn254::{Bn254G1Affine as G1Affine, Bn254G2Affine as G2Affine},
};

#[cfg(test)]
use contract_types::VerificationKeyBytes;

// Compile-time VK constants generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/vk.rs"));

/// Groth16 verification key for BN254 curve.
#[derive(Clone)]
pub struct VerificationKey {
    pub alpha: G1Affine,
    pub beta: G2Affine,
    pub gamma: G2Affine,
    pub delta: G2Affine,
    pub ic: Vec<G1Affine>,
}

/// Build a [`VerificationKey`] from the compile-time embedded byte constants.
///
/// Used directly in unit tests via [`crate::CircomGroth16Verifier::verify_with_vk`].
#[cfg(test)]
pub(crate) fn verification_key_from_bytes(
    env: &Env,
    vk_bytes: &VerificationKeyBytes,
) -> VerificationKey {
    let mut ic_vec: Vec<G1Affine> = Vec::new(env);
    for bytes in vk_bytes.ic.iter() {
        ic_vec.push_back(G1Affine::from_bytes(bytes));
    }

    VerificationKey {
        alpha: G1Affine::from_bytes(vk_bytes.alpha.clone()),
        beta: G2Affine::from_bytes(vk_bytes.beta.clone()),
        gamma: G2Affine::from_bytes(vk_bytes.gamma.clone()),
        delta: G2Affine::from_bytes(vk_bytes.delta.clone()),
        ic: ic_vec,
    }
}

/// Build the [`VerificationKey`] from the constants embedded in the WASM.
pub(crate) fn embedded_vk(env: &Env) -> VerificationKey {
    let mut ic_vec: Vec<G1Affine> = Vec::new(env);
    for bytes in VK_IC.iter() {
        ic_vec.push_back(G1Affine::from_bytes(BytesN::from_array(env, bytes)));
    }
    VerificationKey {
        alpha: G1Affine::from_bytes(BytesN::from_array(env, &VK_ALPHA_G1)),
        beta: G2Affine::from_bytes(BytesN::from_array(env, &VK_BETA_G2)),
        gamma: G2Affine::from_bytes(BytesN::from_array(env, &VK_GAMMA_G2)),
        delta: G2Affine::from_bytes(BytesN::from_array(env, &VK_DELTA_G2)),
        ic: ic_vec,
    }
}
