[workspace]
members = [
    "circuit-keys",
    "contracts/asp-membership",
    "contracts/types",
    "contracts/soroban-utils",
    "contracts/mock-verifier",
    "contracts/pool",
    "contracts/verifier",
    "poseidon2",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
repository = "https://github.com/veil-private-payment/veil-contract"
license = "Apache-2.0"
publish = false

[workspace.dependencies]
asp-membership = { path = "contracts/asp-membership" }
anyhow = { version = "1", default-features = false }
ark-bn254 = { version = "0.6.0", default-features = false, features = ["curve"] }
ark-circom = { git = "https://github.com/NethermindEth/circom-compat.git", default-features = false, branch = "wasm-no-parallel" }
ark-ec = { version = "0.6.0", default-features = false }
ark-ff = { version = "0.6.0", default-features = false }
ark-groth16 = { version = "0.6.0", default-features = false }
ark-relations = { version = "0.6.0", default-features = false }
ark-serialize = { version = "0.6.0", default-features = false }
ark-snark = { version = "0.6.0", default-features = false }
ark-std = { version = "0.6.0", default-features = false, features = ["std"] }
circom-groth16-verifier = { path = "contracts/verifier" }
circuit-keys = { path = "circuit-keys" }
cfg-if = { version = "1", default-features = false }
contract-types = { path = "contracts/types" }
getrandom = { version = "0.2", default-features = false }
hex = { version = "0.4", default-features = false, features = ["alloc"] }
mock-verifier = { path = "contracts/mock-verifier" }
num-bigint = { version = "0.4.6", default-features = false, features = ["serde"] }
pool = { path = "contracts/pool" }
serde_json = { version = "1", default-features = false }
sha2 = { version = "0.11.0", default-features = false }
soroban-utils = { path = "contracts/soroban-utils" }
zkhash = { path = "poseidon2" }
soroban-sdk = { version = "26", default-features = false, features = ["hazmat"] }

[workspace.lints.rust]
missing_docs = "allow"
unsafe_code = "deny"

[workspace.lints.clippy]
arithmetic_side_effects = "deny"
cast_lossless = "deny"
cast_possible_truncation = "deny"
cast_possible_wrap = "deny"
cast_precision_loss = "deny"
cast_sign_loss = "deny"
needless_return = "deny"
panicking_overflow_checks = "deny"
unwrap_used = "deny"
