[package]
name = "zkhash"
version = "0.2.0"
authors = [
    "Markus Schofnegger <mschofnegger@horizenlabs.io>",
    "Roman Walch <roman.walch@iaik.tugraz.at>",
]
description = "Rust implementations of Poseidon2 and similar arithmetization-oriented primitives"
edition = "2018"
license = "Apache-2.0 OR MIT"

[features]
default = []
asm = ["ark-ff/asm"]

[dependencies]
ark-ff = { workspace = true }
ark-std = { workspace = true }
cfg-if = { workspace = true }
hex = { workspace = true }
lazy_static = "1.5"
rand = "0.8"
sha2 = { workspace = true }
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
getrandom = { workspace = true, features = ["std"] }
[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { workspace = true, features = ["js"] }
